// Feste Kategorien, Kategorie-Gruppen und eingebaute Zuordnungsregeln.

import type { Rule } from "./types";

export const CATS = [
  "Einkommen",
  "Sonstige Einnahmen",
  "Lebensmittel",
  "Sprit",
  "Mobilität",
  "Drogerie",
  "Freizeit & Essen",
  "Shopping",
  "Gesundheit",
  "Haus & Garten",
  "Kinder",
  "Urlaub",
  "Wohnen",
  "Kredite & Darlehen",
  "Nebenkosten & Energie",
  "Versicherungen",
  "Abos",
  "Steuern & Abgaben",
  "Umbuchung / Sparen",
  "Sonstiges",
];
export const TRANSFER = "Umbuchung / Sparen";
export const FIXCATS = ["Wohnen", "Kredite & Darlehen", "Nebenkosten & Energie", "Versicherungen", "Abos", "Steuern & Abgaben"];
export const INCATS = ["Einkommen", "Sonstige Einnahmen"];
export const EXPCATS = CATS.filter((c) => !INCATS.includes(c) && c !== TRANSFER);
/** Schnellwahl-Kacheln im Buchen-Dialog. */
export const TILES = [
  "Lebensmittel",
  "Sprit",
  "Drogerie",
  "Freizeit & Essen",
  "Shopping",
  "Gesundheit",
  "Haus & Garten",
  "Kinder",
  "Sonstiges",
];
/** Kategorien, die nie als Fixkosten vorgeschlagen werden. */
export const NOSUG = [
  "Lebensmittel",
  "Sprit",
  "Drogerie",
  "Freizeit & Essen",
  "Shopping",
  "Haus & Garten",
  "Urlaub",
  "Sonstige Einnahmen",
  "Einkommen",
];

export const PERIOD_TYPES = [
  "Elterngeld (Basis)",
  "ElterngeldPlus",
  "Krankengeld",
  "ALG I",
  "ALG I (mit Kind)",
  "Teilzeit / Sonstiges",
  "Zusatzeinkommen",
  "Zusatzausgabe",
];
export const ADD_TYPES = ["Zusatzeinkommen", "Zusatzausgabe"];
export const INTERVALS = [
  { v: 1, l: "monatlich" },
  { v: 3, l: "quartalsweise" },
  { v: 6, l: "halbjährlich" },
  { v: 12, l: "jährlich" },
];
export const IVL: Record<number, string> = { 0: "einmalig", 1: "monatlich", 3: "vierteljährlich", 6: "halbjährlich", 12: "jährlich" };

/** Standard-Grenze für einmalige Buchungen in Euro. */
export const ONEOFF_LIMIT = 2500;
/** Standard: Buchungen ab diesem Tag zählen zum Folgemonat. */
export const CUTOFF_DAY = 25;
/** Standard-Startdatum für den Bankabruf (aus dem Prototyp übernommen). */
export const BANK_SINCE = "2026-09-29";

const R = (m: string, c: string, s?: number): Rule => ({ m, c, s: s || 0 });

/**
 * Eingebaute Regeln. Eigene Regeln der Nutzer gelten vorher.
 * Reihenfolge ist wichtig: die erste passende Regel gewinnt.
 */
export const DEFAULT_RULES: Rule[] = [

  R("lohn/gehalt", "Einkommen", 1),
  R("gehalt", "Einkommen", 1),
  R("bezuege", "Einkommen", 1),
  R("bezüge", "Einkommen", 1),
  R("leistung vom", "Einkommen", 1),
  R("elterngeld", "Einkommen", 1),
  R("kindergeld", "Einkommen", 1),
  R("familienkasse", "Einkommen", 1),
  R("finanzamt", "Sonstige Einnahmen", 1),
  R("finanzamt", "Steuern & Abgaben", -1),
  R("grundbesitzabgaben", "Steuern & Abgaben"),
  R("rundfunk", "Steuern & Abgaben"),
  R("sparen", "Umbuchung / Sparen"),
  R("umbuchung", "Umbuchung / Sparen"),
  R("übertrag", "Umbuchung / Sparen"),
  R("miete", "Wohnen"),
  R("nebenkostenguthaben", "Wohnen"),
  R("darlehensauszahlung", "Kredite & Darlehen"),
  R("darl.-leistung", "Kredite & Darlehen"),
  R("darlehen", "Kredite & Darlehen"),
  R("ca auto bank", "Kredite & Darlehen"),
  R("rate per", "Kredite & Darlehen"),
  R("abschlag gas", "Nebenkosten & Energie", -1),
  R("abschlag strom", "Nebenkosten & Energie", -1),
  R("containerservice", "Haus & Garten"),
  R("bodenbeläge", "Haus & Garten"),
  R("leuchten", "Haus & Garten"),
  R("ikea", "Haus & Garten"),
  R("ingenieurbüro", "Haus & Garten"),
  R("stadtwerke", "Nebenkosten & Energie"),
  R("strom", "Nebenkosten & Energie"),
  R("wasser", "Nebenkosten & Energie"),
  R("kww", "Nebenkosten & Energie"),
  R("deichverband", "Nebenkosten & Energie"),
  R("telekom", "Nebenkosten & Energie"),
  R("vodafone", "Nebenkosten & Energie"),
  R("telefonica", "Nebenkosten & Energie"),
  R("o2 ", "Nebenkosten & Energie"),
  R("versicherung", "Versicherungen"),
  R("barmenia", "Versicherungen"),
  R("beamtenversicher", "Versicherungen"),
  R("bayerische", "Versicherungen"),
  R("badiebayerische", "Versicherungen"),
  R("krankenzus", "Versicherungen"),
  R("huk", "Versicherungen"),
  R("allianz", "Versicherungen"),
  R("ergo", "Versicherungen"),
  R("devk", "Versicherungen"),
  R("netflix", "Abos"),
  R("spotify", "Abos"),
  R("disney", "Abos"),
  R("amznprime", "Abos"),
  R("primevideo", "Abos"),
  R("prime video", "Abos"),
  R("dazn", "Abos"),
  R("apple.com", "Abos"),
  R("edeka", "Lebensmittel"),
  R("rewe", "Lebensmittel"),
  R("aldi", "Lebensmittel"),
  R("lidl", "Lebensmittel"),
  R("penny", "Lebensmittel"),
  R("netto marken", "Lebensmittel"),
  R("kaufland", "Lebensmittel"),
  R("metzgerei", "Lebensmittel"),
  R("bäckerei", "Lebensmittel"),
  R("baeckerei", "Lebensmittel"),
  R("brueggemeier", "Lebensmittel"),
  R("buesch", "Lebensmittel"),
  R("hofladen", "Lebensmittel"),
  R("trinkgut", "Lebensmittel"),
  R("getränke", "Lebensmittel"),
  R("aral", "Sprit"),
  R("hem tankstelle", "Sprit"),
  R("hem ", "Sprit"),
  R("total service station", "Sprit"),
  R("shell", "Sprit"),
  R("esso", "Sprit"),
  R("tankstelle", "Sprit"),
  R("totalenergies", "Sprit"),
  R("avia", "Sprit"),
  R("jet ", "Sprit"),
  R("raiffeisen tank", "Sprit"),
  R("dm-drogerie", "Drogerie"),
  R("dm drogerie", "Drogerie"),
  R("friseur", "Drogerie"),
  R("beauty", "Drogerie"),
  R("rossmann", "Drogerie"),
  R("apotheke", "Gesundheit"),
  R("arzt", "Gesundheit"),
  R("panmedica", "Gesundheit"),
  R("db vertrieb", "Mobilität"),
  R("parkos", "Mobilität"),
  R("parken", "Mobilität"),
  R("parkhaus", "Mobilität"),
  R("deutschlandticket", "Mobilität"),
  R("airbnb", "Urlaub"),
  R("tui ", "Urlaub"),
  R("sixt", "Urlaub"),
  R("rent.car", "Urlaub"),
  R("unterkunft", "Urlaub"),
  R("check24", "Urlaub"),
  R("booking", "Urlaub"),
  R("hotel", "Urlaub"),
  R("gastronomie", "Freizeit & Essen"),
  R("burger king", "Freizeit & Essen"),
  R("mcdonald", "Freizeit & Essen"),
  R("pizza", "Freizeit & Essen"),
  R("kebap", "Freizeit & Essen"),
  R("chikurin", "Freizeit & Essen"),
  R("restaurant", "Freizeit & Essen"),
  R("kaffee", "Freizeit & Essen"),
  R("cafe", "Freizeit & Essen"),
  R("buchhandlung", "Freizeit & Essen"),
  R("hagebau", "Haus & Garten"),
  R("obi", "Haus & Garten"),
  R("bauhaus", "Haus & Garten"),
  R("toom", "Haus & Garten"),
  R("gartenbau", "Haus & Garten"),
  R("blumen", "Haus & Garten"),
  R("amazon", "Shopping"),
  R("amzn", "Shopping"),
  R("zalando", "Shopping"),
  R("mediamarkt", "Shopping"),
  R("saturn", "Shopping"),
  R("etsy", "Shopping"),
  R("otto payments", "Shopping"),
  R("new balance", "Shopping"),
  R("ggs ", "Kinder"),
  R("schule", "Kinder"),
  R("kita", "Kinder"),
];
